{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-petclinic-ingress
spec:
  rules:
    - host: api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "service-common.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}