apigateway:
  enabled: true
  fullnameOverride: api-gateway
  image:
    repository: tqthuan2504/api-gateway
    tag: "latest"
  service:
    port: 3000
  ingress:
    enabled: true
    className: "traefik"
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - host: petclinic.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
user:
  enabled: true
  fullnameOverride: user-service
  image:
    repository: tqthuan2504/user-service
    tag: "latest"
  service:
    port: 3001
  ingress:
    enabled: false